      MODULE GWFWELMODULE
        IMPLICIT NONE
        INTEGER,SAVE,POINTER:: NWELLS
        INTEGER,SAVE,POINTER:: MXWELL
        INTEGER,SAVE,POINTER:: NWELVL
        INTEGER,SAVE,POINTER:: IWELCB
        INTEGER,SAVE,POINTER:: IPRWEL
        INTEGER,SAVE,POINTER:: NPWEL
        INTEGER,SAVE,POINTER:: IWELPB
        INTEGER,SAVE,POINTER:: NNPWEL
        CHARACTER(LEN=16),SAVE, DIMENSION(:),   POINTER     ::WELAUX
        REAL,             SAVE, DIMENSION(:,:), POINTER     ::WELL
      TYPE GWFWELTYPE
        INTEGER,POINTER:: NWELLS
        INTEGER,POINTER:: MXWELL
        INTEGER,POINTER:: NWELVL
        INTEGER,POINTER:: IWELCB
        INTEGER,POINTER:: IPRWEL
        INTEGER,POINTER:: NPWEL
        INTEGER,POINTER:: IWELPB
        INTEGER,POINTER:: NNPWEL
        CHARACTER(LEN=16), DIMENSION(:),   POINTER     ::WELAUX
        REAL,              DIMENSION(:,:), POINTER     ::WELL
      END TYPE
      TYPE(GWFWELTYPE), SAVE:: GWFWELDAT(10)
      END MODULE GWFWELMODULE


      SUBROUTINE GWF2WEL7AR(IN,IGRID)
!     ******************************************************************
!     ALLOCATE ARRAY STORAGE FOR WELL PACKAGE
!     ******************************************************************
!
!        SPECIFICATIONS:
!     ------------------------------------------------------------------
      USE GLOBAL,       ONLY:IOUT,NCOL,NROW,NLAY,IFREFM
      USE GWFWELMODULE, ONLY:NWELLS,MXWELL,NWELVL,IWELCB,IPRWEL,NPWEL,&
     &                       IWELPB,NNPWEL,WELAUX,WELL
!
      IMPLICIT NONE
      INTEGER :: I
      INTEGER :: IGRID
      INTEGER :: IN
      INTEGER :: IP
      INTEGER :: ISTART
      INTEGER :: ISTOP
      INTEGER :: K
      INTEGER :: LLOC
      INTEGER :: LSTBEG
      INTEGER :: LSTSUM
      INTEGER :: MXACTW
      INTEGER :: MXPW
      INTEGER :: N
      INTEGER :: NAUX
      INTEGER :: NINLST
      INTEGER :: NLST
      INTEGER :: NUMINST
      REAL :: R
      CHARACTER*200 LINE
!     ------------------------------------------------------------------
      ALLOCATE(NWELLS,MXWELL,NWELVL,IWELCB,IPRWEL)
      ALLOCATE(NPWEL,IWELPB,NNPWEL)
!
!1------IDENTIFY PACKAGE AND INITIALIZE NWELLS.
      WRITE(IOUT,1)IN
1     FORMAT(1X,/1X,'WEL -- WELL PACKAGE, VERSION 7, 5/2/2005',&
     &' INPUT READ FROM UNIT ',I4)
      NWELLS=0
      NNPWEL=0
!
!2------READ MAXIMUM NUMBER OF WELLS AND UNIT OR FLAG FOR
!2------CELL-BY-CELL FLOW TERMS.
      CALL URDCOM(IN,IOUT,LINE)
      CALL UPARLSTAL(IN,IOUT,LINE,NPWEL,MXPW)
      IF(IFREFM.EQ.0) THEN
         READ(LINE,'(2I10)') MXACTW,IWELCB
         LLOC=21
      ELSE
         LLOC=1
         CALL URWORD(LINE,LLOC,ISTART,ISTOP,2,MXACTW,R,IOUT,IN)
         CALL URWORD(LINE,LLOC,ISTART,ISTOP,2,IWELCB,R,IOUT,IN)
      END IF
      WRITE(IOUT,3) MXACTW
3     FORMAT(1X,'MAXIMUM OF ',I6,' ACTIVE WELLS AT ONE TIME')
      IF(IWELCB.LT.0) WRITE(IOUT,7)
7     FORMAT(1X,'CELL-BY-CELL FLOWS WILL BE PRINTED WHEN ICBCFL NOT 0')
      IF(IWELCB.GT.0) WRITE(IOUT,8) IWELCB
8     FORMAT(1X,'CELL-BY-CELL FLOWS WILL BE SAVED ON UNIT ',I4)
!
!3------READ AUXILIARY VARIABLES AND PRINT FLAG.
      ALLOCATE(WELAUX(20))
      NAUX=0
      IPRWEL=1
10    CALL URWORD(LINE,LLOC,ISTART,ISTOP,1,N,R,IOUT,IN)
      IF(LINE(ISTART:ISTOP).EQ.'AUXILIARY' .OR.&
     &        LINE(ISTART:ISTOP).EQ.'AUX') THEN
         CALL URWORD(LINE,LLOC,ISTART,ISTOP,1,N,R,IOUT,IN)
         IF(NAUX.LT.20) THEN
            NAUX=NAUX+1
            WELAUX(NAUX)=LINE(ISTART:ISTOP)
            WRITE(IOUT,12) WELAUX(NAUX)
12          FORMAT(1X,'AUXILIARY WELL VARIABLE: ',A)
         END IF
         GO TO 10
      ELSE IF(LINE(ISTART:ISTOP).EQ.'NOPRINT') THEN
         WRITE(IOUT,13)
13       FORMAT(1X,'LISTS OF WELL CELLS WILL NOT BE PRINTED')
         IPRWEL = 0
         GO TO 10
      END IF
!3A-----THERE ARE FOUR INPUT VALUES PLUS ONE LOCATION FOR
!3A-----CELL-BY-CELL FLOW.
      NWELVL=5+NAUX
!
!4------ALLOCATE SPACE FOR THE WELL DATA.
      IWELPB=MXACTW+1
      MXWELL=MXACTW+MXPW
      ALLOCATE (WELL(NWELVL,MXWELL))
!
!5------READ NAMED PARAMETERS.
      WRITE(IOUT,18) NPWEL
18    FORMAT(1X,//1X,I5,' Well parameters')
      IF(NPWEL.GT.0) THEN
        LSTSUM=IWELPB
        DO 120 K=1,NPWEL
          LSTBEG=LSTSUM
          CALL UPARLSTRP(LSTSUM,MXWELL,IN,IOUT,IP,'WEL','Q',1,&
     &                   NUMINST)
          NLST=LSTSUM-LSTBEG
          IF(NUMINST.EQ.0) THEN
!5A-----READ PARAMETER WITHOUT INSTANCES.
            CALL ULSTRD(NLST,WELL,LSTBEG,NWELVL,MXWELL,1,IN,&
     &        IOUT,'WELL NO.  LAYER   ROW   COL   STRESS FACTOR',&
     &        WELAUX,20,NAUX,IFREFM,NCOL,NROW,NLAY,4,4,IPRWEL)
          ELSE
!5B-----READ INSTANCES.
            NINLST=NLST/NUMINST
            DO 110 I=1,NUMINST
            CALL UINSRP(I,IN,IOUT,IP,IPRWEL)
            CALL ULSTRD(NINLST,WELL,LSTBEG,NWELVL,MXWELL,1,IN,&
     &        IOUT,'WELL NO.  LAYER   ROW   COL   STRESS FACTOR',&
     &        WELAUX,20,NAUX,IFREFM,NCOL,NROW,NLAY,4,4,IPRWEL)
            LSTBEG=LSTBEG+NINLST
110         CONTINUE
          END IF
120     CONTINUE
      END IF
!
!6------RETURN
      CALL SGWF2WEL7PSV(IGRID)
      RETURN
      END
      SUBROUTINE GWF2WEL7RP(IN,IGRID)
!     ******************************************************************
!     READ WELL DATA FOR A STRESS PERIOD
!     ******************************************************************
!
!        SPECIFICATIONS:
!     ------------------------------------------------------------------
      USE GLOBAL,       ONLY:IOUT,NCOL,NROW,NLAY,IFREFM
      USE GWFWELMODULE, ONLY:NWELLS,MXWELL,NWELVL,IPRWEL,NPWEL,&
     &                       IWELPB,NNPWEL,WELAUX,WELL
!
      IMPLICIT NONE
      INTEGER :: IGRID
      INTEGER :: IN
      INTEGER :: IOUTU
      INTEGER :: ITMP
      INTEGER :: MXACTW
      INTEGER :: N
      INTEGER :: NAUX
      INTEGER :: NP
      INTEGER :: NREAD
      CHARACTER*6 CWELL
!     ------------------------------------------------------------------
      CALL SGWF2WEL7PNT(IGRID)
!
!1----READ NUMBER OF WELLS (OR FLAG SAYING REUSE WELL DATA).
!1----AND NUMBER OF PARAMETERS
      IF(NPWEL.GT.0) THEN
        IF(IFREFM.EQ.0) THEN
           READ(IN,'(2I10)') ITMP,NP
        ELSE
           READ(IN,*) ITMP,NP
        END IF
      ELSE
         NP=0
         IF(IFREFM.EQ.0) THEN
            READ(IN,'(I10)') ITMP
         ELSE
            READ(IN,*) ITMP
         END IF
      END IF
!
!------Calculate some constants.
      NAUX=NWELVL-5
      IOUTU = IOUT
      IF (IPRWEL.EQ.0) IOUTU=-IOUTU
!
!1A-----IF ITMP LESS THAN ZERO REUSE NON-PARAMETER DATA. PRINT MESSAGE.
!1A-----IF ITMP=>0, SET NUMBER OF NON-PARAMETER WELLS EQUAL TO ITMP.
      IF(ITMP.LT.0) THEN
         WRITE(IOUT,6)
6        FORMAT(1X,/&
     &    1X,'REUSING NON-PARAMETER WELLS FROM LAST STRESS PERIOD')
      ELSE
         NNPWEL=ITMP
      END IF
!
!1B-----IF THERE ARE NEW NON-PARAMETER WELLS, READ THEM.
      MXACTW=IWELPB-1
      IF(ITMP.GT.0) THEN
         IF(NNPWEL.GT.MXACTW) THEN
            WRITE(IOUT,99) NNPWEL,MXACTW
99          FORMAT(1X,/1X,'THE NUMBER OF ACTIVE WELLS (',I6,&
     &                     ') IS GREATER THAN MXACTW(',I6,')')
            CALL USTOP(' ')
         END IF
         CALL ULSTRD(NNPWEL,WELL,1,NWELVL,MXWELL,1,IN,IOUT,&
     &            'WELL NO.  LAYER   ROW   COL   STRESS RATE',&
     &             WELAUX,20,NAUX,IFREFM,NCOL,NROW,NLAY,4,4,IPRWEL)
      END IF
      NWELLS=NNPWEL
!
!1C-----IF THERE ARE ACTIVE WELL PARAMETERS, READ THEM AND SUBSTITUTE
      CALL PRESET('Q')
      NREAD=NWELVL-1
      IF(NP.GT.0) THEN
         DO 30 N=1,NP
         CALL UPARLSTSUB(IN,'WEL',IOUTU,'Q',WELL,NWELVL,MXWELL,NREAD,&
     &                MXACTW,NWELLS,4,4,&
     &            'WELL NO.  LAYER   ROW   COL   STRESS RATE',&
     &            WELAUX,20,NAUX)
30       CONTINUE
      END IF
!
!3------PRINT NUMBER OF WELLS IN CURRENT STRESS PERIOD.
      CWELL=' WELLS'
      IF(NWELLS.EQ.1) CWELL=' WELL '
      WRITE(IOUT,101) NWELLS,CWELL
101   FORMAT(1X,/1X,I6,A)
!
!6------RETURN
      RETURN
      END
      SUBROUTINE GWF2WEL7FM(IGRID)
!     ******************************************************************
!     SUBTRACT Q FROM RHS
!     ******************************************************************
!
!        SPECIFICATIONS:
!     ------------------------------------------------------------------
      USE GLOBAL,       ONLY:IBOUND,RHS,HCOF
      USE GWFWELMODULE, ONLY:NWELLS,WELL
!     ------------------------------------------------------------------
      IMPLICIT NONE
      INTEGER :: IC
      INTEGER :: IGRID
      INTEGER :: IL
      INTEGER :: IR
      INTEGER :: L
      REAL :: Q
      CALL SGWF2WEL7PNT(IGRID)
!
!1------IF NUMBER OF WELLS <= 0 THEN RETURN.
      IF(NWELLS.LE.0) RETURN
!
!2------PROCESS EACH WELL IN THE WELL LIST.
      DO 100 L=1,NWELLS
      IR=WELL(2,L)
      IC=WELL(3,L)
      IL=WELL(1,L)
      Q=WELL(4,L)
!
!2A-----IF THE CELL IS INACTIVE THEN BYPASS PROCESSING.
      IF(IBOUND(IC,IR,IL).LE.0) GO TO 100
!
!2B-----IF THE CELL IS VARIABLE HEAD THEN SUBTRACT Q FROM
!       THE RHS ACCUMULATOR.
      RHS(IC,IR,IL)=RHS(IC,IR,IL)-Q
100   CONTINUE
!
!3------RETURN
      RETURN
      END
      SUBROUTINE GWF2WEL7BD(KSTP,KPER,IGRID)
!     ******************************************************************
!     CALCULATE VOLUMETRIC BUDGET FOR WELLS
!     ******************************************************************
!
!        SPECIFICATIONS:
!     ------------------------------------------------------------------
      USE GLOBAL,      ONLY:IOUT,NCOL,NROW,NLAY,IBOUND,BUFF
      USE GWFBASMODULE,ONLY:MSUM,ICBCFL,IAUXSV,DELT,PERTIM,TOTIM,&
     &                      VBVL,VBNM
      USE GWFWELMODULE,ONLY:NWELLS,IWELCB,WELL,NWELVL,WELAUX
!
      IMPLICIT NONE
      INTEGER :: IBD
      INTEGER :: IBDLBL
      INTEGER :: IC
      INTEGER :: IGRID
      INTEGER :: IL
      INTEGER :: IR
      INTEGER :: KPER
      INTEGER :: KSTP
      INTEGER :: L
      INTEGER :: NAUX
      REAL :: Q
      REAL :: RIN
      REAL :: ROUT
      REAL :: ZERO
      CHARACTER*16 TEXT
      SAVE :: TEXT
      DOUBLE PRECISION RATIN
      DOUBLE PRECISION RATOUT
      DOUBLE PRECISION QQ
      DATA TEXT /'           WELLS'/
!     ------------------------------------------------------------------
      CALL SGWF2WEL7PNT(IGRID)
!
!1------CLEAR RATIN AND RATOUT ACCUMULATORS, AND SET CELL-BY-CELL
!1------BUDGET FLAG.
      ZERO=0.
      RATIN=ZERO
      RATOUT=ZERO
      IBD=0
      IF(IWELCB.LT.0 .AND. ICBCFL.NE.0) IBD=-1
      IF(IWELCB.GT.0) IBD=ICBCFL
      IBDLBL=0
!
!2-----IF CELL-BY-CELL FLOWS WILL BE SAVED AS A LIST, WRITE HEADER.
      IF(IBD.EQ.2) THEN
         NAUX=NWELVL-5
         IF(IAUXSV.EQ.0) NAUX=0
         CALL UBDSV4(KSTP,KPER,TEXT,NAUX,WELAUX,IWELCB,NCOL,NROW,NLAY,&
     &          NWELLS,IOUT,DELT,PERTIM,TOTIM,IBOUND)
      END IF
!
!3------CLEAR THE BUFFER.
      DO 50 IL=1,NLAY
      DO 50 IR=1,NROW
      DO 50 IC=1,NCOL
      BUFF(IC,IR,IL)=ZERO
50    CONTINUE
!
!4------IF THERE ARE NO WELLS, DO NOT ACCUMULATE FLOW.
      IF(NWELLS.EQ.0) GO TO 200
!
!5------LOOP THROUGH EACH WELL CALCULATING FLOW.
      DO 100 L=1,NWELLS
!
!5A-----GET LAYER, ROW & COLUMN OF CELL CONTAINING WELL.
      IR=WELL(2,L)
      IC=WELL(3,L)
      IL=WELL(1,L)
      Q=ZERO
!
!5B-----IF THE CELL IS NO-FLOW OR CONSTANT_HEAD, IGNORE IT.
      IF(IBOUND(IC,IR,IL).LE.0)GO TO 99
!
!5C-----GET FLOW RATE FROM WELL LIST.
      Q=WELL(4,L)
      QQ=Q
!
!5D-----PRINT FLOW RATE IF REQUESTED.
      IF(IBD.LT.0) THEN
         IF(IBDLBL.EQ.0) WRITE(IOUT,61) TEXT,KPER,KSTP
61       FORMAT(1X,/1X,A,'   PERIOD ',I4,'   STEP ',I3)
         WRITE(IOUT,62) L,IL,IR,IC,Q
62       FORMAT(1X,'WELL ',I6,'   LAYER ',I3,'   ROW ',I5,'   COL ',I5,&
     &       '   RATE ',1PG15.6)
         IBDLBL=1
      END IF
!
!5E-----ADD FLOW RATE TO BUFFER.
      BUFF(IC,IR,IL)=BUFF(IC,IR,IL)+Q
!
!5F-----SEE IF FLOW IS POSITIVE OR NEGATIVE.
      IF(Q.GE.ZERO) THEN
!
!5G-----FLOW RATE IS POSITIVE (RECHARGE). ADD IT TO RATIN.
        RATIN=RATIN+QQ
      ELSE
!
!5H-----FLOW RATE IS NEGATIVE (DISCHARGE). ADD IT TO RATOUT.
        RATOUT=RATOUT-QQ
      END IF
!
!5I-----IF SAVING CELL-BY-CELL FLOWS IN A LIST, WRITE FLOW.  ALSO
!5I-----COPY FLOW TO WELL LIST.
99    IF(IBD.EQ.2) CALL UBDSVB(IWELCB,NCOL,NROW,IC,IR,IL,Q,&
     &                  WELL(:,L),NWELVL,NAUX,5,IBOUND,NLAY)
      WELL(NWELVL,L)=Q
100   CONTINUE
!
!6------IF CELL-BY-CELL FLOWS WILL BE SAVED AS A 3-D ARRAY,
!6------CALL UBUDSV TO SAVE THEM.
      IF(IBD.EQ.1) CALL UBUDSV(KSTP,KPER,TEXT,IWELCB,BUFF,NCOL,NROW,&
     &                          NLAY,IOUT)
!
!7------MOVE RATES, VOLUMES & LABELS INTO ARRAYS FOR PRINTING.
200   RIN=RATIN
      ROUT=RATOUT
      VBVL(3,MSUM)=RIN
      VBVL(4,MSUM)=ROUT
      VBVL(1,MSUM)=VBVL(1,MSUM)+RIN*DELT
      VBVL(2,MSUM)=VBVL(2,MSUM)+ROUT*DELT
      VBNM(MSUM)=TEXT
!
!8------INCREMENT BUDGET TERM COUNTER(MSUM).
      MSUM=MSUM+1
!
!9------RETURN
      RETURN
      END
      SUBROUTINE GWF2WEL7DA(IGRID)
!  Deallocate WEL MEMORY
      USE GWFWELMODULE
!
      IMPLICIT NONE
      INTEGER :: IGRID
        CALL SGWF2WEL7PNT(IGRID)
        DEALLOCATE(NWELLS)
        DEALLOCATE(MXWELL)
        DEALLOCATE(NWELVL)
        DEALLOCATE(IWELCB)
        DEALLOCATE(IPRWEL)
        DEALLOCATE(NPWEL)
        DEALLOCATE(IWELPB)
        DEALLOCATE(NNPWEL)
        DEALLOCATE(WELAUX)
        DEALLOCATE(WELL)
!
      RETURN
      END
      SUBROUTINE SGWF2WEL7PNT(IGRID)
!  Change WEL data to a different grid.
      USE GWFWELMODULE
!
      IMPLICIT NONE
      INTEGER :: IGRID
        NWELLS=>GWFWELDAT(IGRID)%NWELLS
        MXWELL=>GWFWELDAT(IGRID)%MXWELL
        NWELVL=>GWFWELDAT(IGRID)%NWELVL
        IWELCB=>GWFWELDAT(IGRID)%IWELCB
        IPRWEL=>GWFWELDAT(IGRID)%IPRWEL
        NPWEL=>GWFWELDAT(IGRID)%NPWEL
        IWELPB=>GWFWELDAT(IGRID)%IWELPB
        NNPWEL=>GWFWELDAT(IGRID)%NNPWEL
        WELAUX=>GWFWELDAT(IGRID)%WELAUX
        WELL=>GWFWELDAT(IGRID)%WELL
!
      RETURN
      END
      SUBROUTINE SGWF2WEL7PSV(IGRID)
!  Save WEL data for a grid.
      USE GWFWELMODULE
!
      IMPLICIT NONE
      INTEGER :: IGRID
        GWFWELDAT(IGRID)%NWELLS=>NWELLS
        GWFWELDAT(IGRID)%MXWELL=>MXWELL
        GWFWELDAT(IGRID)%NWELVL=>NWELVL
        GWFWELDAT(IGRID)%IWELCB=>IWELCB
        GWFWELDAT(IGRID)%IPRWEL=>IPRWEL
        GWFWELDAT(IGRID)%NPWEL=>NPWEL
        GWFWELDAT(IGRID)%IWELPB=>IWELPB
        GWFWELDAT(IGRID)%NNPWEL=>NNPWEL
        GWFWELDAT(IGRID)%WELAUX=>WELAUX
        GWFWELDAT(IGRID)%WELL=>WELL
!
      RETURN
      END
