      MODULE GWFLAKMODULE
!------OLD USGS VERSION 7.1; JUNE 2006 GWFLAKMODULE; 
!------UPDATED FOR MF-2005, 1.9 RELEASE, FEBRUARY 6, 2012  
!------REVISION NUMBER CHANGED TO BE CONSISTENT WITH NWT RELEASE
!------NEW VERSION NUMBER 1.1.3, 8/01/2017  
!------MINOR UPDATES JAN. 2013 (LFK)
        IMPLICIT NONE
        CHARACTER(LEN=64),PARAMETER ::Version_lak =&
     &'$Id: gwf2lak7_NWT.f 2370 2014-07-01 17:35:48Z rniswon $'
        INTEGER,SAVE,POINTER:: NLAKES
        INTEGER,SAVE,POINTER:: NLAKESAR
        INTEGER,SAVE,POINTER:: ILKCB
        INTEGER,SAVE,POINTER:: NSSITR
        INTEGER,SAVE,POINTER:: LAKUNIT
        INTEGER,SAVE,POINTER:: MXLKND
        INTEGER,SAVE,POINTER:: LKNODE
        INTEGER,SAVE,POINTER:: ICMX
        INTEGER,SAVE,POINTER:: NCLS
        INTEGER,SAVE,POINTER:: LWRT
        INTEGER,SAVE,POINTER:: NDV
        INTEGER,SAVE,POINTER:: NTRB
        INTEGER,SAVE,POINTER:: IRDTAB
        REAL,SAVE,POINTER:: THETA
        REAL,SAVE,POINTER:: SSCNCR
        REAL,SAVE,POINTER:: SURFDEPTH
!dep    Added SURFDEPTH  3/3/2009
!rgn    Added budget variables for GSFLOW CSV file
        REAL,SAVE,POINTER:: TOTGWIN_LAK
        REAL,SAVE,POINTER:: TOTGWOT_LAK
        REAL,SAVE,POINTER:: TOTDELSTOR_LAK
        REAL,SAVE,POINTER:: TOTSTOR_LAK
        REAL,SAVE,POINTER:: TOTEVAP_LAK
        REAL,SAVE,POINTER:: TOTPPT_LAK
        REAL,SAVE,POINTER:: TOTRUNF_LAK
        REAL,SAVE,POINTER:: TOTWTHDRW_LAK
        REAL,SAVE,POINTER:: TOTSURFIN_LAK
        REAL,   SAVE,POINTER   ::TOTSURFOT_LAK
        INTEGER,SAVE,DIMENSION(:),POINTER:: ICS
        INTEGER,SAVE,DIMENSION(:),POINTER:: NCNCVR
        INTEGER,SAVE,DIMENSION(:),POINTER:: LIMERR
        INTEGER,SAVE,DIMENSION(:),POINTER:: LAKTAB
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: ILAKE
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: ITRB
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: IDIV
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: ISUB
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: IRK
        INTEGER,SAVE, DIMENSION(:,:,:),POINTER ::LKARR1
        REAL,   SAVE, DIMENSION(:),  POINTER ::STAGES
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: STGNEW
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: STGOLD
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: STGITER
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: VOLOLDD
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: STGOLD2
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: RUNF  !EDM
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: RUNOFF
        INTEGER,SAVE,                POINTER ::NLKFLWTYP
        CHARACTER*16, SAVE, DIMENSION(:), POINTER :: LKFLOWTYPE
        REAL,SAVE,DIMENSION(:),POINTER:: VOL
        REAL,SAVE,DIMENSION(:),POINTER:: FLOB
        REAL,SAVE,DIMENSION(:),POINTER:: DSRFOT
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: PRCPLK
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: EVAPLK
        REAL,   SAVE, DIMENSION(:),  POINTER ::BEDLAK
        REAL,SAVE,DIMENSION(:),POINTER:: WTHDRW
        REAL,SAVE,DIMENSION(:),POINTER:: RNF
        REAL,SAVE,DIMENSION(:),POINTER:: CUMRNF
        REAL,SAVE,DIMENSION(:),POINTER:: CUMPPT
        REAL,SAVE,DIMENSION(:),POINTER:: CUMEVP
        REAL,SAVE,DIMENSION(:),POINTER:: CUMGWI
        REAL,   SAVE, DIMENSION(:),  POINTER ::CUMUZF
        REAL,SAVE,DIMENSION(:),POINTER:: CUMGWO
        REAL,SAVE,DIMENSION(:),POINTER:: CUMSWI
        REAL,SAVE,DIMENSION(:),POINTER:: CUMSWO
        REAL,SAVE,DIMENSION(:),POINTER:: CUMWDR
        REAL,SAVE,DIMENSION(:),POINTER:: CUMFLX
        REAL,SAVE,DIMENSION(:),POINTER:: CNDFCT
        REAL,   SAVE, DIMENSION(:),  POINTER ::VOLINIT
        REAL,SAVE,DIMENSION(:),POINTER:: BOTTMS
        REAL,SAVE,DIMENSION(:),POINTER:: BGAREA
        REAL,SAVE,DIMENSION(:),POINTER:: SSMN
        REAL,SAVE,DIMENSION(:),POINTER:: SSMX
!dep    Added cumulative and time step error budget arrays
        REAL,SAVE,DIMENSION(:),POINTER:: CUMVOL
        REAL,SAVE,DIMENSION(:),POINTER:: CMLAKERR
        REAL,SAVE,DIMENSION(:),POINTER:: CUMLKOUT
        REAL,SAVE,DIMENSION(:),POINTER:: CUMLKIN
        REAL,SAVE,DIMENSION(:),POINTER:: TSLAKERR
        REAL,SAVE,DIMENSION(:),POINTER:: DELVOL
!rgn        REAL,   SAVE, DIMENSION(:),  POINTER ::EVAP,PRECIP,SEEP,SEEP3
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: EVAP
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: PRECIP
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: EVAP3
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: PRECIP3
        DOUBLE PRECISION,   SAVE, DIMENSION(:),  POINTER ::FLWITER
        DOUBLE PRECISION,   SAVE, DIMENSION(:),  POINTER ::FLWITER3
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: SEEP
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: SEEP3
        DOUBLE PRECISION,   SAVE, DIMENSION(:),  POINTER ::SEEPUZ
        DOUBLE PRECISION,   SAVE, DIMENSION(:),  POINTER ::WITHDRW
        DOUBLE PRECISION,   SAVE, DIMENSION(:),  POINTER ::SURFA
        REAL,SAVE,DIMENSION(:),POINTER:: SURFOT
        REAL,SAVE,DIMENSION(:),POINTER:: SURFIN
        REAL,SAVE,DIMENSION(:),POINTER:: SUMCNN
        REAL,SAVE,DIMENSION(:),POINTER:: SUMCHN
        REAL,SAVE,DIMENSION(:,:),POINTER:: CLAKE
        REAL,SAVE,DIMENSION(:,:),POINTER:: CRNF
        REAL,SAVE,DIMENSION(:,:),POINTER:: SILLVT
        REAL,SAVE,DIMENSION(:,:),POINTER:: CAUG
        REAL,SAVE,DIMENSION(:,:),POINTER:: CPPT
        REAL,SAVE,DIMENSION(:,:),POINTER:: CLAKINIT
        REAL,   SAVE, DIMENSION(:,:,:),POINTER ::BDLKN1
!dep  Added arrays for tracking lake budgets for dry lakes
        REAL,SAVE,DIMENSION(:),POINTER:: EVAPO
        REAL,SAVE,DIMENSION(:),POINTER:: FLWIN
        REAL,   SAVE, DIMENSION(:),  POINTER ::GWRATELIM
!dep    Allocate arrays to add runoff from UZF Package
        REAL,SAVE,DIMENSION(:),POINTER:: OVRLNDRNF
        REAL,SAVE,DIMENSION(:),POINTER:: CUMLNDRNF
!dep    Allocate arrays for lake depth, area,and volume relations
        DOUBLE PRECISION,   SAVE, DIMENSION(:,:),  POINTER ::DEPTHTABLE
        DOUBLE PRECISION,   SAVE, DIMENSION(:,:),  POINTER ::AREATABLE
        DOUBLE PRECISION,   SAVE, DIMENSION(:,:),  POINTER ::VOLUMETABLE
!dep    Allocate space for three dummy arrays used in GAGE Package
!         when Solute Transport is active
        REAL,SAVE,DIMENSION(:,:),POINTER:: XLAKES
        REAL,SAVE,DIMENSION(:,:),POINTER:: XLAKINIT
        REAL,SAVE,DIMENSION(:,:),POINTER:: XLKOLD
!rsr    Allocate arrays in BD subroutine
        INTEGER,SAVE,DIMENSION(:),POINTER:: LDRY
        INTEGER,SAVE,DIMENSION(:),POINTER:: NCNT
        INTEGER,SAVE,DIMENSION(:),POINTER:: NCNST
        INTEGER,SAVE,DIMENSION(:),POINTER:: KSUB
        INTEGER,SAVE, DIMENSION(:),  POINTER ::MSUB1
        INTEGER,SAVE, DIMENSION(:,:),POINTER ::MSUB
        REAL,SAVE,DIMENSION(:),POINTER:: FLXINL
        REAL,SAVE,DIMENSION(:),POINTER:: VOLOLD
        REAL,SAVE,DIMENSION(:),POINTER:: GWIN
        REAL,SAVE,DIMENSION(:),POINTER:: GWOUT
        REAL,SAVE,DIMENSION(:),POINTER:: DELH
        REAL,SAVE,DIMENSION(:),POINTER:: TDELH
        REAL,SAVE,DIMENSION(:),POINTER:: SVT
        REAL,SAVE,DIMENSION(:),POINTER:: STGADJ
        REAL,   SAVE, DIMENSION(:,:),POINTER ::LAKSEEP
        INTEGER,SAVE,                POINTER ::NSFRLAK !EDM
        INTEGER,SAVE,DIMENSION(:),POINTER:: LAKSFR  !EDM
        INTEGER,SAVE,DIMENSION(:),POINTER:: ILKSEG
        INTEGER,SAVE,DIMENSION(:),POINTER:: ILKRCH
        REAL,SAVE,DIMENSION(:),POINTER:: SWLAK  !EDM
        REAL,SAVE,DIMENSION(:),POINTER:: DELVOLLAK
      TYPE GWFLAKTYPE
        INTEGER,POINTER:: NLAKES
        INTEGER,POINTER:: NLAKESAR
        INTEGER,POINTER:: ILKCB
        INTEGER,POINTER:: NSSITR
        INTEGER,POINTER:: LAKUNIT
        INTEGER,POINTER:: MXLKND
        INTEGER,POINTER:: LKNODE
        INTEGER,POINTER:: ICMX
        INTEGER,POINTER:: NCLS
        INTEGER,POINTER:: LWRT
        INTEGER,POINTER:: NDV
        INTEGER,POINTER:: NTRB
        INTEGER,POINTER:: IRDTAB
!dep    Added SURFDEPTH 3/3/2009
        REAL,POINTER:: THETA
        REAL,POINTER:: SSCNCR
        REAL,POINTER:: SURFDEPTH
!rgn    Added budget variables for GSFLOW CSV file
        REAL,POINTER:: TOTGWIN_LAK
        REAL,POINTER:: TOTGWOT_LAK
        REAL,POINTER:: TOTDELSTOR_LAK
        REAL,POINTER:: TOTSTOR_LAK
        REAL,POINTER:: TOTEVAP_LAK
        REAL,POINTER:: TOTPPT_LAK
        REAL,POINTER:: TOTRUNF_LAK
        REAL,POINTER:: TOTWTHDRW_LAK
        REAL,POINTER:: TOTSURFOT_LAK
        REAL,POINTER:: TOTSURFIN_LAK
        INTEGER,DIMENSION(:),POINTER:: ICS
        INTEGER,DIMENSION(:),POINTER:: NCNCVR
        INTEGER,DIMENSION(:),POINTER:: LIMERR
        INTEGER,DIMENSION(:),POINTER:: LAKTAB
        INTEGER,DIMENSION(:,:),POINTER:: ILAKE
        INTEGER,DIMENSION(:,:),POINTER:: ITRB
        INTEGER,DIMENSION(:,:),POINTER:: IDIV
        INTEGER,DIMENSION(:,:),POINTER:: ISUB
        INTEGER,DIMENSION(:,:),POINTER:: IRK
        INTEGER,      DIMENSION(:,:,:),POINTER ::LKARR1
        REAL,         DIMENSION(:),  POINTER ::STAGES
        DOUBLE PRECISION,DIMENSION(:),POINTER:: STGNEW
        DOUBLE PRECISION,DIMENSION(:),POINTER:: STGOLD
        DOUBLE PRECISION,DIMENSION(:),POINTER:: STGITER
        DOUBLE PRECISION,DIMENSION(:),POINTER:: STGOLD2
        DOUBLE PRECISION,DIMENSION(:),POINTER:: RUNF  !EDM
        DOUBLE PRECISION,DIMENSION(:),POINTER:: RUNOFF
        CHARACTER*16, DIMENSION(:), POINTER :: LKFLOWTYPE
        INTEGER,                    POINTER :: NLKFLWTYP
        DOUBLE PRECISION,DIMENSION(:),POINTER :: VOLOLDD
        REAL,DIMENSION(:),POINTER:: VOL
        REAL,DIMENSION(:),POINTER:: FLOB
        REAL,DIMENSION(:),POINTER:: DSRFOT
        DOUBLE PRECISION,DIMENSION(:),POINTER:: PRCPLK
        DOUBLE PRECISION,DIMENSION(:),POINTER:: EVAPLK
        REAL,         DIMENSION(:),  POINTER ::BEDLAK
        REAL,DIMENSION(:),POINTER:: WTHDRW
        REAL,DIMENSION(:),POINTER:: RNF
        REAL,DIMENSION(:),POINTER:: CUMRNF
        REAL,DIMENSION(:),POINTER:: CUMPPT
        REAL,DIMENSION(:),POINTER:: CUMEVP
        REAL,DIMENSION(:),POINTER:: CUMGWI
        REAL,         DIMENSION(:),  POINTER ::CUMUZF
        REAL,DIMENSION(:),POINTER:: CUMGWO
        REAL,DIMENSION(:),POINTER:: CUMSWI
        REAL,DIMENSION(:),POINTER:: CUMSWO
        REAL,DIMENSION(:),POINTER:: CUMWDR
        REAL,DIMENSION(:),POINTER:: CUMFLX
        REAL,DIMENSION(:),POINTER:: CNDFCT
        REAL,         DIMENSION(:),  POINTER ::VOLINIT
        REAL,DIMENSION(:),POINTER:: BOTTMS
        REAL,DIMENSION(:),POINTER:: BGAREA
        REAL,DIMENSION(:),POINTER:: SSMN
        REAL,DIMENSION(:),POINTER:: SSMX
!dep    Added cumulative and time step error budget arrays
        REAL,DIMENSION(:),POINTER:: CUMVOL
        REAL,DIMENSION(:),POINTER:: CMLAKERR
        REAL,DIMENSION(:),POINTER:: CUMLKOUT
        REAL,DIMENSION(:),POINTER:: TSLAKERR
        REAL,DIMENSION(:),POINTER:: DELVOL
        REAL,DIMENSION(:),POINTER:: CUMLKIN
!rgn        REAL,         DIMENSION(:),  POINTER ::EVAP,PRECIP,SEEP,SEEP3
        DOUBLE PRECISION,DIMENSION(:),POINTER:: EVAP
        DOUBLE PRECISION,DIMENSION(:),POINTER:: PRECIP
        DOUBLE PRECISION,DIMENSION(:),POINTER:: EVAP3
        DOUBLE PRECISION,DIMENSION(:),POINTER:: PRECIP3
        DOUBLE PRECISION,DIMENSION(:),  POINTER :: FLWITER
        DOUBLE PRECISION,DIMENSION(:),  POINTER :: FLWITER3
        DOUBLE PRECISION,DIMENSION(:),POINTER:: SEEP
        DOUBLE PRECISION,DIMENSION(:),POINTER:: SEEP3
        DOUBLE PRECISION,DIMENSION(:),  POINTER :: SEEPUZ
        DOUBLE PRECISION,DIMENSION(:),  POINTER :: WITHDRW
        DOUBLE PRECISION,DIMENSION(:),  POINTER :: SURFA
        REAL,DIMENSION(:),POINTER:: SURFIN
        REAL,DIMENSION(:),POINTER:: SURFOT
        REAL,DIMENSION(:),POINTER:: SUMCNN
        REAL,DIMENSION(:),POINTER:: SUMCHN
        REAL,DIMENSION(:,:),POINTER:: CLAKE
        REAL,DIMENSION(:,:),POINTER:: CRNF
        REAL,DIMENSION(:,:),POINTER:: SILLVT
        REAL,DIMENSION(:,:),POINTER:: CAUG
        REAL,DIMENSION(:,:),POINTER:: CPPT
        REAL,DIMENSION(:,:),POINTER:: CLAKINIT
        REAL,         DIMENSION(:,:,:),POINTER ::BDLKN1
!dep  Added arrays for tracking lake budgets for dry lakes
        REAL,DIMENSION(:),POINTER:: EVAPO
        REAL,DIMENSION(:),POINTER:: FLWIN
        REAL,         DIMENSION(:),  POINTER ::GWRATELIM
!dep    Allocate arrays to add runoff from UZF Package
        REAL,DIMENSION(:),POINTER:: OVRLNDRNF
        REAL,DIMENSION(:),POINTER:: CUMLNDRNF
!dep    Allocate arrays for lake depth, area, and volume relations
        DOUBLE PRECISION,         DIMENSION(:,:),POINTER ::DEPTHTABLE
        DOUBLE PRECISION,         DIMENSION(:,:),POINTER ::AREATABLE
        DOUBLE PRECISION,         DIMENSION(:,:),POINTER ::VOLUMETABLE
!dep    Allocate space for three dummy arrays used in GAGE Package
!         when Solute Transport is active
        REAL,DIMENSION(:,:),POINTER:: XLAKES
        REAL,DIMENSION(:,:),POINTER:: XLAKINIT
        REAL,DIMENSION(:,:),POINTER:: XLKOLD
!rsr    Allocate arrays in BD subroutine
        INTEGER,DIMENSION(:),POINTER:: LDRY
        INTEGER,DIMENSION(:),POINTER:: NCNT
        INTEGER,DIMENSION(:),POINTER:: NCNST
        INTEGER,DIMENSION(:),POINTER:: KSUB
        INTEGER,      DIMENSION(:),  POINTER ::MSUB1
        INTEGER,      DIMENSION(:,:),POINTER ::MSUB
        REAL,DIMENSION(:),POINTER:: FLXINL
        REAL,DIMENSION(:),POINTER:: VOLOLD
        REAL,DIMENSION(:),POINTER:: GWIN
        REAL,DIMENSION(:),POINTER:: GWOUT
        REAL,DIMENSION(:),POINTER:: DELH
        REAL,DIMENSION(:),POINTER:: TDELH
        REAL,DIMENSION(:),POINTER:: SVT
        REAL,DIMENSION(:),POINTER:: STGADJ
        REAL,         DIMENSION(:,:),POINTER ::LAKSEEP
        INTEGER,                     POINTER ::NSFRLAK !EDM
        INTEGER,DIMENSION(:),POINTER:: LAKSFR  !EDM
        INTEGER,DIMENSION(:),POINTER:: ILKSEG
        INTEGER,DIMENSION(:),POINTER:: ILKRCH
        REAL,DIMENSION(:),POINTER:: SWLAK  !EDM
        REAL,DIMENSION(:),POINTER:: DELVOLLAK
      END TYPE
      TYPE(GWFLAKTYPE), SAVE:: GWFLAKDAT(10)
      END MODULE GWFLAKMODULE
