      MODULE GWFSFRMODULE
        IMPLICIT NONE
        CHARACTER(LEN=64), SAVE :: Version_sfr
        DOUBLE PRECISION,PARAMETER :: NEARZERO=1.0D-30
        DOUBLE PRECISION,SAVE:: THETAB
        DOUBLE PRECISION,SAVE:: FLUXB
        DOUBLE PRECISION,SAVE:: FLUXHLD2
        REAL,PARAMETER :: CLOSEZERO=1.0E-15
        INTEGER,SAVE,POINTER:: STRHC1KHFLAG
        INTEGER,SAVE,POINTER:: STRHC1KVFLAG
        INTEGER,SAVE,POINTER:: Nfoldflbt
        INTEGER,SAVE,POINTER:: NUMTAB
        INTEGER,SAVE,POINTER:: MAXVAL
        INTEGER,SAVE,                 POINTER:: IDVFLG !diversion recharge is active flag
        INTEGER,SAVE,                 POINTER:: NFLOWTYPE
        CHARACTER*16, SAVE, DIMENSION(:), POINTER :: FLOWTYPE
        INTEGER,SAVE,POINTER:: NSS
        INTEGER,SAVE,POINTER:: NSTRM
        INTEGER,SAVE,POINTER:: NSFRPAR
        INTEGER,SAVE,POINTER:: ISTCB1
        INTEGER,SAVE,POINTER:: ISTCB2
        INTEGER,SAVE,POINTER:: IUZT
        INTEGER,SAVE,POINTER:: MAXPTS
        INTEGER,SAVE,POINTER:: IRTFLG
        INTEGER,SAVE,POINTER:: NUMTIM
        INTEGER,SAVE,POINTER:: NSEGDIM
        INTEGER,SAVE,POINTER:: ISFROPT
        INTEGER,SAVE,POINTER:: NSTRAIL
        INTEGER,SAVE,POINTER:: ISUZN
        INTEGER,SAVE,POINTER:: NSFRSETS
        INTEGER,SAVE,POINTER:: NUZST
        INTEGER,SAVE,POINTER:: NSTOTRL
        INTEGER,SAVE,POINTER:: NUMAVE
        INTEGER,SAVE,POINTER:: ITMP
        INTEGER,SAVE,POINTER:: IRDFLG
        INTEGER,SAVE,POINTER:: IPTFLG
        INTEGER,SAVE,POINTER:: NP
        REAL,SAVE,POINTER:: CONST
        REAL,SAVE,POINTER:: DLEAK
        REAL,SAVE,POINTER:: WEIGHT
        REAL,SAVE,POINTER:: SFRRATIN
        REAL,SAVE,POINTER:: SFRRATOUT
        REAL,SAVE,POINTER:: FLWTOL
        REAL,SAVE,POINTER:: STRMDELSTOR_CUM
        REAL,SAVE,POINTER:: STRMDELSTOR_RATE
        REAL,SAVE,POINTER:: FACTORKH
        REAL,SAVE,POINTER:: FACTORKV
        REAL,SAVE,POINTER:: FACTOR
        REAL,SAVE,POINTER:: SFRUZINFIL
        REAL,SAVE,POINTER:: SFRUZDELSTOR
        REAL,SAVE,POINTER:: SFRUZRECH
        DOUBLE PRECISION,SAVE,POINTER:: TOTSPFLOW
        INTEGER,SAVE,DIMENSION(:),POINTER:: IOTSG
        INTEGER,SAVE,DIMENSION(:),POINTER:: NSEGCK
        INTEGER,SAVE,  DIMENSION(:),  POINTER:: ITRLSTH
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: ISEG
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: IDIVAR
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: ISTRM
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: LTRLIT
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: LTRLST
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: ITRLIT
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: ITRLST
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: NWAVST
        REAL,SAVE,DIMENSION(:),POINTER:: STRIN
        REAL,SAVE,DIMENSION(:),POINTER:: STROUT
        REAL,SAVE,DIMENSION(:),POINTER:: FXLKOT
        REAL,SAVE,DIMENSION(:),POINTER:: UHC
        REAL,SAVE,DIMENSION(:),POINTER:: SGOTFLW
        REAL,SAVE,DIMENSION(:),POINTER:: DVRSFLW
        REAL,   SAVE,  DIMENSION(:),  POINTER:: SFRUZBD
        REAL,SAVE,DIMENSION(:,:),POINTER:: SEG
        REAL,SAVE,DIMENSION(:,:),POINTER:: STRM
        REAL,SAVE,DIMENSION(:,:),POINTER:: SFRQ
        REAL,SAVE,DIMENSION(:,:),POINTER:: HWDTH
        REAL,SAVE,DIMENSION(:,:),POINTER:: HWTPRM
        REAL,SAVE,DIMENSION(:,:),POINTER:: QSTAGE
        REAL,SAVE,DIMENSION(:,:),POINTER:: XSEC
        REAL,SAVE,DIMENSION(:,:),POINTER:: AVDPT
        REAL,SAVE,DIMENSION(:,:),POINTER:: AVWAT
        REAL,SAVE,DIMENSION(:,:),POINTER:: WAT1
        REAL,SAVE,DIMENSION(:,:),POINTER:: CONCQ
        REAL,SAVE,DIMENSION(:,:),POINTER:: CONCRUN
        REAL,SAVE,DIMENSION(:,:),POINTER:: CONCPPT
        REAL,SAVE,DIMENSION(:,:),POINTER:: TABFLOW  !Reading Specified inflow
        REAL,SAVE,DIMENSION(:,:),POINTER:: TABTIME
        REAL,   SAVE,  DIMENSION(:,:),POINTER:: FNETSEEP !writing net seepage in UZF
        INTEGER,SAVE,  DIMENSION(:,:),POINTER:: ISFRLIST !Reading Specified inflow
        INTEGER,SAVE,POINTER:: NINTOT  !for LMT, total # of possible inflows edm 7/30/13
        INTEGER,SAVE,POINTER:: ITRFLG
!        INTEGER,SAVE,                 POINTER:: NFLOWTYPE          !edm
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: THTS
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: THTR
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: EPS
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: FOLDFLBT
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: THTI
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: SUMLEAK
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: SUMRCH
        DOUBLE PRECISION,SAVE,DIMENSION(:),  POINTER:: HLDSFR
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZFLWT
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZSTOR
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZWDTH
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZSEEP
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: DELSTOR
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: WETPER
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZDPIT
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZDPST
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZTHIT
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZTHST
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZSPIT
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZSPST
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZFLIT
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZFLST
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZOLSFLX
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: HSTRM
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: QSTRM
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: SLKOTFLW
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: DLKOTFLW
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: DLKSTAGE
      TYPE GWFSFRTYPE
        INTEGER,POINTER:: STRHC1KHFLAG
        INTEGER,POINTER:: STRHC1KVFLAG
        INTEGER,POINTER:: Nfoldflbt
        INTEGER,POINTER:: NUMTAB
        INTEGER,POINTER:: MAXVAL
        INTEGER,POINTER:: NUMIRRSFR
        INTEGER,POINTER:: UNITIRR
        INTEGER,POINTER:: MAXCELLS
        INTEGER,                      POINTER:: IDVFLG !diversion recharge is active flag
        INTEGER,                      POINTER:: NFLOWTYPE
        CHARACTER*16,  DIMENSION(:),  POINTER:: FLOWTYPE
        INTEGER,POINTER:: NSS
        INTEGER,POINTER:: NSTRM
        INTEGER,POINTER:: NSFRPAR
        INTEGER,POINTER:: ISTCB1
        INTEGER,POINTER:: ISTCB2
        INTEGER,POINTER:: IUZT
        INTEGER,POINTER:: MAXPTS
        INTEGER,POINTER:: IRTFLG
        INTEGER,POINTER:: NUMTIM
        INTEGER,POINTER:: NSEGDIM
        INTEGER,POINTER:: ISFROPT
        INTEGER,POINTER:: NSTRAIL
        INTEGER,POINTER:: ISUZN
        INTEGER,POINTER:: NSFRSETS
        INTEGER,POINTER:: NUZST
        INTEGER,POINTER:: NSTOTRL
        INTEGER,POINTER:: NUMAVE
        INTEGER,POINTER:: ITMP
        INTEGER,POINTER:: IRDFLG
        INTEGER,POINTER:: IPTFLG
        INTEGER,POINTER:: NP
        REAL,POINTER:: CONST
        REAL,POINTER:: DLEAK
        REAL,POINTER:: WEIGHT
        REAL,POINTER:: SFRRATIN
        REAL,POINTER:: SFRRATOUT
        REAL,POINTER:: FLWTOL
        REAL,POINTER:: STRMDELSTOR_CUM
        REAL,POINTER:: STRMDELSTOR_RATE
        REAL,POINTER:: FACTORKH
        REAL,POINTER:: FACTORKV
        REAL,POINTER:: FACTOR
        REAL,POINTER:: SFRUZINFIL
        REAL,POINTER:: SFRUZDELSTOR
        REAL,POINTER:: SFRUZRECH
        DOUBLE PRECISION, POINTER:: TOTSPFLOW
        INTEGER,DIMENSION(:),POINTER:: IOTSG
        INTEGER,DIMENSION(:),POINTER:: NSEGCK
        INTEGER,       DIMENSION(:),  POINTER:: ITRLSTH
        INTEGER,DIMENSION(:,:),POINTER:: ISEG
        INTEGER,DIMENSION(:,:),POINTER:: IDIVAR
        INTEGER,DIMENSION(:,:),POINTER:: ISTRM
        INTEGER,DIMENSION(:,:),POINTER:: LTRLIT
        INTEGER,DIMENSION(:,:),POINTER:: LTRLST
        INTEGER,DIMENSION(:,:),POINTER:: ITRLIT
        INTEGER,DIMENSION(:,:),POINTER:: ITRLST
        INTEGER,DIMENSION(:,:),POINTER:: NWAVST
        REAL,DIMENSION(:),POINTER:: STRIN
        REAL,DIMENSION(:),POINTER:: STROUT
        REAL,DIMENSION(:),POINTER:: FXLKOT
        REAL,DIMENSION(:),POINTER:: UHC
        REAL,DIMENSION(:),POINTER:: SGOTFLW
        REAL,DIMENSION(:),POINTER:: DVRSFLW
        REAL,          DIMENSION(:),  POINTER:: SFRUZBD
        REAL,DIMENSION(:,:),POINTER:: SEG
        REAL,DIMENSION(:,:),POINTER:: STRM
        REAL,DIMENSION(:,:),POINTER:: SFRQ
        REAL,DIMENSION(:,:),POINTER:: HWDTH
        REAL,DIMENSION(:,:),POINTER:: HWTPRM
        REAL,DIMENSION(:,:),POINTER:: QSTAGE
        REAL,DIMENSION(:,:),POINTER:: XSEC
        REAL,DIMENSION(:,:),POINTER:: AVDPT
        REAL,DIMENSION(:,:),POINTER:: AVWAT
        REAL,DIMENSION(:,:),POINTER:: WAT1
        REAL,DIMENSION(:,:),POINTER:: CONCQ
        REAL,DIMENSION(:,:),POINTER:: CONCRUN
        REAL,DIMENSION(:,:),POINTER:: CONCPPT
        REAL,DIMENSION(:,:),POINTER:: TABFLOW  ! Reading SPecified inflow
        REAL,DIMENSION(:,:),POINTER:: TABTIME
        REAL,          DIMENSION(:,:),POINTER:: FNETSEEP !writing net seepage in UZF
        INTEGER,       DIMENSION(:,:),POINTER:: ISFRLIST
        INTEGER,                      POINTER:: NINTOT !for LMT, total # of possible inflows edm 7/30/13
        DOUBLE PRECISION,DIMENSION(:),POINTER:: THTS
        DOUBLE PRECISION,DIMENSION(:),POINTER:: THTR
        DOUBLE PRECISION,DIMENSION(:),POINTER:: EPS
        DOUBLE PRECISION,DIMENSION(:),POINTER:: FOLDFLBT
        DOUBLE PRECISION,DIMENSION(:),POINTER:: THTI
        DOUBLE PRECISION,DIMENSION(:),POINTER:: SUMLEAK
        DOUBLE PRECISION,DIMENSION(:),POINTER:: SUMRCH
        DOUBLE PRECISION,     DIMENSION(:),  POINTER:: HLDSFR
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZFLWT
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZSTOR
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZWDTH
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZSEEP
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: DELSTOR
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: WETPER
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZDPIT
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZDPST
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZTHIT
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZTHST
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZSPIT
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZSPST
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZFLIT
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZFLST
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZOLSFLX
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: HSTRM
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: QSTRM
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: SLKOTFLW
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: DLKOTFLW
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: DLKSTAGE
      END TYPE
      TYPE(GWFSFRTYPE), SAVE:: GWFSFRDAT(10)
      END MODULE GWFSFRMODULE
