      MODULE GWFUZFMODULE
        IMPLICIT NONE
        CHARACTER(LEN=64) :: Version_uzf
        REAL,PARAMETER :: CLOSEZERO=1.0E-15
        DOUBLE PRECISION,PARAMETER :: NEARZERO=1.0D-30
        DOUBLE PRECISION,PARAMETER:: ZEROD15=1.0D-15
        DOUBLE PRECISION,PARAMETER:: ZEROD9=1.0D-09
        DOUBLE PRECISION,PARAMETER :: ZEROD6=1.0D-06
        DOUBLE PRECISION,PARAMETER:: ZEROD7=1.0D-07
        DOUBLE PRECISION,PARAMETER:: ZEROD5=1.0D-05
        INTEGER         ,PARAMETER :: IRUNBIG = 10000
        INTEGER,SAVE,POINTER:: NUMCELLS
        INTEGER,SAVE,POINTER:: TOTCELLS
        INTEGER,SAVE,POINTER:: Iseepsupress
        INTEGER,SAVE,POINTER :: ISAVEFINF
        INTEGER,SAVE,POINTER:: IPRCNT
        INTEGER,SAVE,POINTER:: Ireadsurfk
        INTEGER,SAVE,POINTER:: Isurfkreject
        INTEGER,SAVE, POINTER :: Iseepreject
        INTEGER,SAVE,POINTER:: ITHTIFLG
        INTEGER,SAVE,POINTER:: ITHTRFLG
        INTEGER,SAVE,POINTER:: UNITRECH
        INTEGER,SAVE,POINTER:: UNITDIS
        DOUBLE PRECISION,SAVE:: THETAB
        DOUBLE PRECISION,SAVE:: FLUXB
        DOUBLE PRECISION,SAVE:: FLUXHLD2
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER :: CHECKTIME
        INTEGER,SAVE,DIMENSION(:),POINTER :: MORE
        INTEGER,SAVE,DIMENSION(:,:),POINTER :: LAYNUM
        INTEGER,SAVE,POINTER:: NUZTOP
        INTEGER,SAVE,POINTER:: IUZFOPT
        INTEGER,SAVE,POINTER:: IRUNFLG
        INTEGER,SAVE,POINTER:: IETFLG
        INTEGER,SAVE,POINTER:: IUZM
        INTEGER,SAVE,POINTER:: IUZFCB1
        INTEGER,SAVE,POINTER:: IUZFCB2
        INTEGER,SAVE,POINTER:: NTRAIL
        INTEGER,SAVE,POINTER:: NWAV
        INTEGER,SAVE,POINTER:: NSETS
        INTEGER,SAVE,POINTER:: IUZFB22
        INTEGER,SAVE,POINTER:: IUZFB11
        INTEGER,SAVE,POINTER:: ETOPT
        INTEGER,SAVE,POINTER:: NUZGAG
        INTEGER,SAVE,POINTER:: NUZGAGAR
        INTEGER,SAVE,POINTER:: NUZCL
        INTEGER,SAVE,POINTER:: NUZRW
        INTEGER,SAVE,POINTER:: IGSFLOW
        INTEGER,SAVE,POINTER:: RTSOLUTE
        INTEGER,SAVE,POINTER:: IETBUD
        INTEGER,SAVE,POINTER:: INETFLUX
        INTEGER,SAVE,  DIMENSION(:),    POINTER :: ITRLSTH
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: IRUNBND
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: IUZFBND
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: IUZLIST
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: NWAVST
        INTEGER,SAVE,  DIMENSION(:,:),  POINTER :: IUZHOLD
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: LTRLST
        INTEGER,SAVE,DIMENSION(:,:),POINTER:: ITRLST
        INTEGER,SAVE,DIMENSION(:),POINTER:: LTRLIT
        INTEGER,SAVE,DIMENSION(:),POINTER:: ITRLIT
        REAL,SAVE,POINTER:: TOTRUNOFF
        REAL,SAVE,POINTER:: SURFDEP
        REAL,   SAVE,  DIMENSION(:),    POINTER :: FBINS
        REAL,SAVE,DIMENSION(:,:),POINTER:: SEEPOUT
        REAL,SAVE,DIMENSION(:,:),POINTER:: EXCESPP
        REAL,SAVE,DIMENSION(:,:),POINTER:: VKS
        REAL,   SAVE,  DIMENSION(:,:),  POINTER :: SURFK
        REAL,SAVE,DIMENSION(:,:),POINTER:: AIR_ENTRY
        REAL,SAVE,DIMENSION(:,:),POINTER:: H_ROOT
        REAL,   SAVE,  DIMENSION(:,:),  POINTER :: REJ_INF
        REAL,   SAVE,  DIMENSION(:,:),  POINTER :: TO_CFP
        REAL,SAVE,DIMENSION(:,:),POINTER:: EPS
        REAL,SAVE,DIMENSION(:,:),POINTER:: THTS
        REAL,SAVE,DIMENSION(:,:),POINTER:: THTI
        REAL,SAVE,DIMENSION(:,:),POINTER:: THTR
        REAL,SAVE,DIMENSION(:,:),POINTER:: PETRATE
        REAL,SAVE,DIMENSION(:,:),POINTER:: ROOTDPTH
        REAL,SAVE,DIMENSION(:,:),POINTER:: WCWILT
        REAL,SAVE,DIMENSION(:,:),POINTER:: FINF
        REAL,SAVE,DIMENSION(:,:),POINTER:: FINFSAVE
        REAL,SAVE,DIMENSION(:,:),POINTER:: UZFETOUT
        REAL,SAVE,DIMENSION(:,:),POINTER:: GWET
        REAL,   SAVE,  DIMENSION(:,:),  POINTER :: FNETEXFIL1
        REAL,SAVE,DIMENSION(:,:),POINTER:: FNETEXFIL2
        REAL,SAVE,DIMENSION(:,:),POINTER:: CUMGWET
        REAL,   SAVE,  POINTER :: TIMEPRINT
        DOUBLE PRECISION, SAVE, POINTER :: SMOOTHET
        DOUBLE PRECISION, SAVE, DIMENSION(:),  POINTER :: CUMUZVOL
        DOUBLE PRECISION, SAVE, DIMENSION(:),  POINTER :: UZTSRAT
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZFLWT
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZSTOR
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZDPST
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZTHST
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: UZDPIT
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: UZTHIT
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZSPST
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER:: UZFLST
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: UZSPIT
        DOUBLE PRECISION,SAVE,DIMENSION(:),POINTER:: UZFLIT
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),POINTER :: DELSTOR
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),POINTER :: UZOLSFLX
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),POINTER :: HLDUZF
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),POINTER :: RTSOLWC
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),POINTER :: RTSOLFL
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),POINTER :: RTSOLDS
        DOUBLE PRECISION, SAVE, DIMENSION(:,:,:),POINTER :: UZTOTBAL
        DOUBLE PRECISION, SAVE, DIMENSION(:,:,:),POINTER :: GRIDSTOR
        DOUBLE PRECISION, SAVE, DIMENSION(:,:,:),POINTER :: GRIDET
      TYPE GWFUZFTYPE
        INTEGER,POINTER:: NUZTOP
        INTEGER,POINTER:: IUZFOPT
        INTEGER,POINTER:: IRUNFLG
        INTEGER,POINTER:: IETFLG
        INTEGER,POINTER:: IUZM
        INTEGER,POINTER:: IUZFCB1
        INTEGER,POINTER:: IUZFCB2
        INTEGER,POINTER:: NTRAIL
        INTEGER,POINTER:: NWAV
        INTEGER,POINTER:: NSETS
        INTEGER,POINTER:: IUZFB22
        INTEGER,POINTER:: IUZFB11
        INTEGER,POINTER:: ETOPT
        INTEGER,POINTER:: NUZGAG
        INTEGER,POINTER:: NUZGAGAR
        INTEGER,POINTER:: NUZCL
        INTEGER,POINTER:: NUZRW
        INTEGER,POINTER:: IGSFLOW
        INTEGER,POINTER:: RTSOLUTE
        INTEGER,POINTER:: IETBUD
        INTEGER,POINTER:: INETFLUX
        INTEGER,POINTER:: NUMCELLS
        INTEGER,POINTER:: TOTCELLS
        INTEGER,POINTER:: Iseepsupress
        INTEGER,     POINTER   ::ISAVEFINF
        INTEGER,POINTER:: IPRCNT
        INTEGER,POINTER:: Ireadsurfk
        INTEGER,POINTER:: Isurfkreject
        INTEGER,     POINTER   ::Iseepreject
        INTEGER,POINTER:: ITHTIFLG
        INTEGER,POINTER:: ITHTRFLG
        INTEGER,POINTER:: UNITRECH
        INTEGER,POINTER:: UNITDIS
        DOUBLE PRECISION,DIMENSION(:),  POINTER :: CHECKTIME
        INTEGER,DIMENSION(:),POINTER :: MORE
        INTEGER,DIMENSION(:,:),POINTER :: LAYNUM
        INTEGER,       DIMENSION(:),    POINTER :: ITRLSTH
        INTEGER,DIMENSION(:,:),POINTER:: IRUNBND
        INTEGER,DIMENSION(:,:),POINTER:: IUZFBND
        INTEGER,DIMENSION(:,:),POINTER:: IUZLIST
        INTEGER,DIMENSION(:,:),POINTER:: NWAVST
        INTEGER,       DIMENSION(:,:),  POINTER :: IUZHOLD
        INTEGER,DIMENSION(:,:),POINTER:: LTRLST
        INTEGER,DIMENSION(:,:),POINTER:: ITRLST
        INTEGER,DIMENSION(:),POINTER:: LTRLIT
        INTEGER,DIMENSION(:),POINTER:: ITRLIT
        REAL,POINTER:: TOTRUNOFF
        REAL,POINTER:: SURFDEP
        REAL,          DIMENSION(:),    POINTER :: FBINS
        REAL,DIMENSION(:,:),POINTER:: SEEPOUT
        REAL,DIMENSION(:,:),POINTER:: EXCESPP
        REAL,DIMENSION(:,:),POINTER:: VKS
        REAL,          DIMENSION(:,:),  POINTER :: SURFK
        REAL,DIMENSION(:,:),POINTER:: AIR_ENTRY
        REAL,DIMENSION(:,:),POINTER:: H_ROOT
        REAL,          DIMENSION(:,:),  POINTER :: REJ_INF
        REAL,          DIMENSION(:,:),  POINTER :: TO_CFP
        REAL,DIMENSION(:,:),POINTER:: EPS
        REAL,DIMENSION(:,:),POINTER:: THTS
        REAL,DIMENSION(:,:),POINTER:: THTI
        REAL,DIMENSION(:,:),POINTER:: THTR
        REAL,DIMENSION(:,:),POINTER:: PETRATE
        REAL,DIMENSION(:,:),POINTER:: ROOTDPTH
        REAL,DIMENSION(:,:),POINTER:: WCWILT
        REAL,DIMENSION(:,:),POINTER:: FINF
        REAL,DIMENSION(:,:),POINTER:: FINFSAVE
        REAL,DIMENSION(:,:),POINTER:: UZFETOUT
        REAL,DIMENSION(:,:),POINTER:: GWET
        REAL,          DIMENSION(:,:),  POINTER :: FNETEXFIL1
        REAL,DIMENSION(:,:),POINTER:: FNETEXFIL2
        REAL,DIMENSION(:,:),POINTER:: CUMGWET
        REAL,                           POINTER :: TIMEPRINT
        DOUBLE PRECISION,       POINTER :: SMOOTHET
        DOUBLE PRECISION,       DIMENSION(:),  POINTER :: CUMUZVOL
        DOUBLE PRECISION,       DIMENSION(:),  POINTER :: UZTSRAT
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZFLWT
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZSTOR
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZDPST
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZTHST
        DOUBLE PRECISION,DIMENSION(:),POINTER:: UZDPIT
        DOUBLE PRECISION,DIMENSION(:),POINTER:: UZTHIT
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZSPST
        DOUBLE PRECISION,DIMENSION(:,:),POINTER:: UZFLST
        DOUBLE PRECISION,DIMENSION(:),POINTER:: UZSPIT
        DOUBLE PRECISION,DIMENSION(:),POINTER:: UZFLIT
        DOUBLE PRECISION,       DIMENSION(:,:),POINTER :: DELSTOR
        DOUBLE PRECISION,       DIMENSION(:,:),POINTER :: UZOLSFLX
        DOUBLE PRECISION,       DIMENSION(:,:),POINTER :: HLDUZF
        DOUBLE PRECISION,       DIMENSION(:,:),POINTER :: RTSOLWC
        DOUBLE PRECISION,       DIMENSION(:,:),POINTER :: RTSOLFL
        DOUBLE PRECISION,       DIMENSION(:,:),POINTER :: RTSOLDS
        DOUBLE PRECISION,       DIMENSION(:,:,:),POINTER :: UZTOTBAL
        DOUBLE PRECISION,       DIMENSION(:,:,:),POINTER :: GRIDSTOR
        DOUBLE PRECISION,       DIMENSION(:,:,:),POINTER :: GRIDET
      END TYPE
      TYPE(GWFUZFTYPE), SAVE:: GWFUZFDAT(10)
      END MODULE GWFUZFMODULE