subdir('hydprograms')

mf2005_sources = files(
 'ccfd.c',
 'de47.f90',
 'gmg7_c_interface.f90',
 'gmg7.f90',
 'gwf2bas7.f90',
 'gwf2bcf7.f90',
 'gwf2chd7.f90',
 'gwf2drn7.f90',
 'gwf2drt7.f90',
 'gwf2ets7.f90',
 'gwf2evt7.f90',
 'gwf2fhb7.f90',
 'gwf2gag7.f90',
 'gwf2ghb7.f90',
 'gwf2hfb7.f90',
 'gwf2huf7.f90',
 'gwf2hydmod7.f90',
 'gwf2ibs7.f90',
 'gwf2lak7.f90',
 'gwf2lpf7.f90',
 'gwf2mnw2i7.f90',
 'gwf2mnw17.f90',
 'gwf2mnw27.f90',
 'gwf2rch7.f90',
 'gwf2res7.f90',
 'gwf2riv7.f90',
 'gwf2sfr7.f90',
 'gwf2str7.f90',
 'gwf2sub7.f90',
 'gwf2swi27.F90',
 'gwf2swr7.f90',
 'gwf2swr7util.f90',
 'gwf2swt7.f90',
 'gwf2uzf1.f90',
 'gwf2wel7.f90',
 'gwflakmodule.f90',
 'gwfsfrmodule.f90',
 'gwfuzfmodule.f90',
 'hufutl7.f90',
 'lmt8.f90',
 'mf2kgmg.c',
 'mf2005.f90',
 'mhc7.f90',
 'obs2bas7.f90',
 'obs2chd7.f90',
 'obs2drn7.f90',
 'obs2ghb7.f90',
 'obs2riv7.f90',
 'obs2str7.f90',
 'parutl7.f90',
 'pcg7.f90',
 'pcgn_solve2.f90',
 'pcgn2.f90',
 'r_vector.c',
 'sip7.f90',
 'solvers.c',
 'utl7.f90',
)

mf2005 = executable(buildname,
                    mf2005_sources,
                    dependencies: extra_deps,
                    link_language: 'fortran',
                    install: true)
